#!/bin/bash

get_subdomain_info() {
    local domain=$1
    local subdomain=$2

    if [[ -z $subdomain ]]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        result=$(dig $sub.$domain | awk '/ANSWER SECTION/{getline; print}')
        echo "The subdomain $sub is a $(echo $result | awk '{print $4}') record and points to $(echo $result | awk '{print $5}')"
    done
}

# Check for mandatory arguments
if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <domain> [<subdomain>]"
    exit 1
fi

domain=$1
subdomain=$2

get_subdomain_info $domain $subdomain
