#!/usr/bin/env bash
# displays Best School 10 times.
i=1
H="Best School"
while [ $i -lt 11 ]
do
	
	if [ $i = 4 ]
	then
		echo "bad luck"
		elif [ $i = 8 ]
		then
			 echo "good luck"
	else
		echo "$H"
	fi
	((i++))
done
